# Generated by Django 5.2.3 on 2025-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_duty',
            field=models.BooleanField(default=False, verbose_name='Pharmacie de garde'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacies/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True),
        ),
    ]
