# Generated by Django 5.2.3 on 2025-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_pharmacyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='insurance_covered',
        ),
        migrations.AddField(
            model_name='user',
            name='insurance_covered',
            field=models.ManyToManyField(blank=True, related_name='pharmacies', to='App.insurance'),
        ),
    ]
