# Generated by Django 5.2.3 on 2025-07-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
